### ISSUE TITLE
doesn't work with shard.yml

### ISSUE THREAD

**Issue by stakach** [DanSnow/crystal-binary_parser#1]
getting this when I add this project to my shard.yml
![image](https://user-images.githubusercontent.com/368013/52256093-84555300-2969-11e9-998d-53c936555389.png)

Works if I specify the master branch though

```yml
dependencies:
  binary_parser:
    github: DanSnow/crystal-binary_parser
    branch: master
```
